# Generated by Django 6.0.4 on 2026-04-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id_repuesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad_stock', models.PositiveIntegerField(default=0)),
                ('unidad_medida', models.CharField(default='unidades', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'repuesto',
                'verbose_name_plural': 'repuestos',
                'db_table': 'spare_parts',
            },
        ),
    ]
