sonar.projectKey=gmao
sonar.projectName=GMAO - Gestión de Mantenimiento
sonar.projectVersion=1.0

sonar.sources=backend
sonar.exclusions=**/node_modules/**,**/.venv/**,**/migrations/**,**/tests/**,**/__pycache__/**,**/dist/**,**/build/**,**/*.min.js,**/db.sqlite3,backend/manage.py,backend/gmao/wsgi.py,backend/gmao/asgi.py,backend/gmao/settings/**,backend/conftest.py,backend/gmao/urls.py,backend/coverage.xml

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.version=3.11

sonar.host.url=http://localhost:9000
sonar.token=sqp_8f1e2347d4cb13921d32bd11da297645df4ba1e6
