# Generated by Django 6.0.4 on 2026-04-21 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], max_length=20)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En Proceso'), ('CERRADA', 'Cerrada')], default='PROGRAMADO', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('frecuencia', models.CharField(choices=[('UNICA', 'Única'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual')], default='UNICA', max_length=20)),
                ('notas_cierre', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_equipo', models.ForeignKey(db_column='fk_equipo', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='equipment.equipment')),
                ('fk_tecnico', models.ForeignKey(blank=True, db_column='fk_tecnico', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work_orders',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveIntegerField()),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.sparepart')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts_used', to='work_orders.workorder')),
            ],
            options={
                'db_table': 'work_order_spare_parts',
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['fk_equipo', '-fecha_inicio'], name='idx_wo_equipo_fecha'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['estado'], name='idx_wo_estado'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['fk_tecnico'], name='idx_wo_tecnico'),
        ),
        migrations.AlterUniqueTogether(
            name='workordersparepart',
            unique_together={('work_order', 'spare_part')},
        ),
    ]
