# Generated by Django 6.0.4 on 2026-04-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id_unico', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipment',
                'indexes': [models.Index(fields=['tipo'], name='idx_equipment_tipo'), models.Index(fields=['ubicacion'], name='idx_equipment_ubicacion')],
            },
        ),
    ]
